config/routes.rb
Rails.application.routes.draw do
  resources :contacts, :only => [:new, :index, :create] do
  	collection do
      get :thankyou
      get :form
      post :form_submit
    end
  end
  root 'contacts#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  private

    def your_spam_callback_method
      redirect_to root_path
    end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  invisible_captcha only: [:form_submit], honeypot: :subtitle
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.all
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  def form
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)
    respond_to do |format|
      if verify_recaptcha(model: @contact) && @contact.save
        format.html { redirect_to thankyou_contacts_path, notice: 'Contact was successfully created.' }
        format.json { render :show, status: :created, location: @contact }
      else
        format.json { render json: @contact.errors, status: :unprocessable_entity }
        # format.html { redirect_back fallback_location: @contact, source: contact_params[:interest], alert: 'Please try again' }
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def form_submit
    @contact = Contact.new(contact_params)
    respond_to do |format|
      if @contact.save
        format.html { redirect_to thankyou_contacts_path, notice: 'Contact was successfully created.' }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { redirect_back fallback_location: @contact, source: contact_params[:interest], alert: 'Please try again' }
        # format.html { render :new }
        # format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def contact_params
      params.require(:contact).permit(:name, :email, :organization, :country, :subject, :designation, :interest, :message, :phone)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/_form.html.erb
<%= form_for @contact, url: @contact, method: :post, :html=> {name:'new-contact'} do |form| %>
  <% if @contact.errors.any? %>
  <div id="error_explanation">
  <h2><%= pluralize(@contact.errors.count, "error") %> prohibited this contact from being saved:</h2>
  <ul>
  <% @contact.errors.full_messages.each do |message| %>
    <li><%= message %></li>
  <% end %>
  </ul>
  </div>
  <% end %>
  <div class="mobile-margin">
    <h1 class="text-center"><%= t('contact.mail_us')%></h1>
  </div>
  <span class="underline"></span>
  <div class="row">
    <div class="col-lg-6 col-md-6">
      <div class="form-group">
        <%= form.text_field :name, class: "form-control bg-transparent", placeholder: 'Name', required: true %>
      </div>
    </div>

    <div class="col-lg-6 col-md-6">
      <div class="form-group">
        <%= form.email_field :email, class: "form-control bg-transparent", placeholder: 'Email', required: true %>
      </div>
    </div>

    <div class="col-lg-6 col-md-6">
      <div class="form-group">
        <%= form.text_field :organization, class: "form-control bg-transparent", placeholder:'Organization', required: true %>
      </div>
    </div>
    <div class="col-lg-6 col-md-6">
      <div class="form-group">
        <%= form.number_field :phone, class: "form-control bg-transparent", placeholder: 'Phone', required: true %>
      </div>
    </div>
        
    <div class="col-lg-12">
      <div class="form-group">
        <%= recaptcha_tags %>
      </div>
    </div>

    <div class="col-lg-12">
      <div class="form-group">
        <%= form.submit class: "btn btn-primary" %>
      </div>
    </div>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<h1>Editing Contact</h1>

<%= render 'form', contact: @contact %>

<%= link_to 'Show', @contact %> |
<%= link_to 'Back', contacts_path %>

app/views/contacts/form.html.erb
<%= form_for @contact, url: form_submit_contacts_path, method: :post, :html=> {name:'new-contact'} do |form| %>
  <% if @contact.errors.any? %>
  <div id="error_explanation">
  <h2><%= pluralize(@contact.errors.count, "error") %> prohibited this contact from being saved:</h2>
  <ul>
  <% @contact.errors.full_messages.each do |message| %>
    <li><%= message %></li>
  <% end %>
  </ul>
  </div>
  <% end %>
  <div class="mobile-margin">
    <h1 class="text-center"><%= t('contact.mail_us')%></h1>
  </div>
  <span class="underline"></span>
  <div class="row">
    <div class="col-lg-6 col-md-6">
      <div class="form-group">
        <%= form.text_field :name, class: "form-control bg-transparent", placeholder: 'Name', required: true %>
      </div>
    </div>

    <div class="col-lg-6 col-md-6">
      <div class="form-group">
        <%= form.email_field :email, class: "form-control bg-transparent", placeholder: 'Email', required: true %>
      </div>
    </div>

    <div class="col-lg-6 col-md-6">
      <div class="form-group">
        <%= form.text_field :organization, class: "form-control bg-transparent", placeholder:'Organization', required: true %>
      </div>
    </div>
    <div class="col-lg-6 col-md-6">
      <div class="form-group">
        <%= form.number_field :phone, class: "form-control bg-transparent", placeholder: 'Phone', required: true %>
      </div>
    </div>
    <div class="col-lg-12">
      <div class="form-group">
        <%= form.invisible_captcha :subtitle %>
        <%= form.submit class: "btn btn-primary" %>
      </div>
    </div>
  </div>
<% end %>

app/views/contacts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Contacts</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    
  </tbody>
</table>

<br>

<a class="btn btn-primary" href="/contacts/new">Contact form with recaptcha</a>
<a class="btn btn-primary" href="/contacts/form">Contact form with invisible recaptcha</a>

app/views/contacts/new.html.erb
<h1>New Contact</h1><a href='/contacts/form' class="btn btn-primary">Form With Invisible Recaptach</a>

<%= render 'form', contact: @contact %>

<%= link_to 'Back', contacts_path %>

<!-- 
<section class="pt-4 pb-4 contact">
  <div class="container-fluid">
    <div class="row no-gutters">
      <div class="col-sm-8">
        <div class="d-none d-sm-block">
          <p class="text-center"><%#= image_tag("map.svg", alt: "map", class: "img-fluid") %></p>
        </div>
        <div class="row no-gutters">
          <%#= render 'form', contact: @contact %>
        </div>
      </div>
      <div class="col-sm-1 d-none d-sm-block"><%#= image_tag("divider.svg", alt: "divider", class: "img-fluid") %></div>
    </div>
  </div>
</section>
 -->

app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_contact_path(@contact) %> |
<%= link_to 'Back', contacts_path %>

app/views/contacts/thankyou.html.erb
<p>Thankyou for submission</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Demo</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<% if notice %>
    <div class="container-fluid">
      <div class="position-absolute w-75 z-index-alert">
        <div class="alert alert-primary alert-dismissible alert-position" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <%= notice %>
        </div>
      </div>
    </div>
    <% end %>
    <% if alert %>
    <div class="container-fluid">
      <div class="position-absolute w-75 z-index-alert">
        <div class="alert alert-danger alert-dismissible alert-position" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <%= alert %>
        </div>
      </div>
    </div>
    <% end %>
    <%= flash[:error] %>
    <%= yield %>
  </body>
</html>